name: sample-nodejs-kafka
envs:
  - scope: RUN_TIME
    type: GENERAL
    key: KAFKA_BROKER
  - scope: RUN_TIME
    type: GENERAL
    key: KAFKA_TOPIC
  - scope: RUN_TIME
    type: GENERAL
    key: KAFKA_USERNAME
  - scope: RUN_TIME
    type: GENERAL
    key: KAFKA_PASSWORD
  - scope: RUN_TIME
    type: GENERAL
    key: KAFKA_CA_CERT
services:
  - name: producer
    source_dir: producer
    github:
      repo: digitalocean/sample-nodejs-kafka
      branch: main
workers:
  - name: consumer
    source_dir: consumer
    github:
      repo: digitalocean/sample-nodejs-kafka
      branch: main
